module.exports = {
    tabWidth: 4,
    singleQuote: true,
    semi: true,
    trailingComma: 'all',
    bracketSpacing: false,
    printWidth: 140,
    bracketSameLine: true,
    jsxSingleQuote: false,
    arrowParens: 'always',
    useTabs: false,
    quoteProps: 'as-needed',
    insertPragma: false,
    proseWrap: 'preserve',
    htmlWhitespaceSensitivity: 'css',
    vueIndentScriptAndStyle: false,
    endOfLine: 'lf',
    embeddedLanguageFormatting: 'auto',
    singleAttributePerLine: false,
};
